FROM node:16.20-alpine3.17


ARG POSTGRES_HOST
ENV POSTGRES_HOST $POSTGRES_HOST

ARG POSTGRES_USER
ENV POSTGRES_USER $POSTGRES_USER

ARG POSTGRES_DATABASE
ENV POSTGRES_DATABASE $POSTGRES_DATABASE

ARG POSTGRES_PORT
ENV POSTGRES_PORT $POSTGRES_PORT

ARG POSTGRES_PASSWORD
ENV POSTGRES_PASSWORD $POSTGRES_PASSWORD


RUN mkdir -p /home/app

COPY dashboard-web-application/server /home/app

EXPOSE 5000

CMD POSTGRES_HOST=$POSTGRES_HOST POSTGRES_USER=$POSTGRES_USER POSTGRES_DATABASE=$POSTGRES_DATABASE POSTGRES_PORT=$POSTGRES_PORT POSTGRES_PASSWORD=$POSTGRES_PASSWORD node /home/app/index.js